int tconst(void);
int bitNand(int x, int y);
int getByte(int x,int y);
int roundUp(int x);
int swapOddandEven(int x);
int secondLowBit(int x);
int rotateNBits(int x, int n);
int fractions(int x);
int biggerOrEqual(int x, int y);
int hdOverflow(int x,int y);
int overflowCalc(int x, int y, int z);
int partialFill(int l, int h);
unsigned float_abs(unsigned uf);
unsigned float_i2f(int x);
int oddParity(int x);

int test_tconst(void);
int test_bitNand(int x, int y);
int test_getByte(int x,int y);
int test_roundUp(int x);
int test_swapOddandEven(int x);
int test_secondLowBit(int x);
int test_rotateNBits(int x, int n);
int test_fractions(int x);
int test_biggerOrEqual(int x, int y);
int test_hdOverflow(int x,int y);
int test_overflowCalc(int x, int y, int z);
int test_partialFill(int l, int h);
unsigned test_float_abs(unsigned uf);
unsigned test_float_i2f(int x);
int test_oddParity(int x);
