int tconst(void);
int bitNand(int x, int y);
int getByte(int x,int y);
int roundUp(int x);
int swapOddandEven(int x);
int secondLowBit(int x);
int rotateNBits(int x, int n);
int fractions(int x);
int biggerOrEqual(int x, int y);
int hdOverflow(int x,int y);
int overflowCalc(int x, int y, int z);
int partialFill(int l, int h);
unsigned float_abs(unsigned uf);
unsigned float_i2f(int x);
int oddParity(int x);
int bitNor(int x, int y);
int tmin(void);
int absVal(int x);
int leastBitPos(int x);
int greatestBitPos(int x);
int isLessOrEqual(int x, int y);
int multSevenSixteens(int x);
int bitCount(int x);
int logicalShift(int x, int n);
int minusOne(void);
unsigned float_neg(unsigned uf);
unsigned float_twice(unsigned uf)

int test_tconst(void);
int test_bitNand(int x, int y);
int test_getByte(int x,int y);
int test_roundUp(int x);
int test_swapOddandEven(int x);
int test_secondLowBit(int x);
int test_rotateNBits(int x, int n);
int test_fractions(int x);
int test_biggerOrEqual(int x, int y);
int test_hdOverflow(int x,int y);
int test_overflowCalc(int x, int y, int z);
int test_partialFill(int l, int h);
unsigned test_float_abs(unsigned uf);
unsigned test_float_i2f(int x);
int test_oddParity(int x);
int test_bitNor(int x, int y);
int test_tmin(void);
int test_absVal(int x);
int test_leastBitPos(int x);
int test_greatestBitPos(int x);
int test_isLessOrEqual(int x, int y);
int test_multSevenSixteens(int x);
int test_bitCount(int x);
int test_logicalShift(int x, int n);
int test_minusOne(void);
unsigned test_float_neg(unsigned uf);
unsigned test_float_twice(unsigned uf)
